services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 8080:80
    volumes:
      - ./frontend:/usr/local/apache2/htdocs

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend/app.sh:/app.sh

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306

  phpMyadmin:
    image: phpmyadmin:latest
    container_name: phpMyadmin
    environment:
      PMA_HOST: db
    ports:
      - 8081:80
    depends_on:
      - db
