version: "3.8"

services: # commentaire pour forcer un conflit
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 8080:80
    volumes:
      - ./frontend:/usr/local/apache2/htdocs
